# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Clone
      run: git clone https://github.com/Alluxio/alluxio
    - run: cd alluxio
    
    - name: Checkout latest commit
      uses: actions/checkout@v3
      with:
        repository: Alluxio/alluxio
        ref: 68fcda9dd2ca2181eb897e10ca02fa5bc3a3099f
    - name: Build with Maven
      run: mvn clean install -DskipTests -pl core/server/worker -am
    - name: Test without NonDex
      run: mvn -pl core/server/worker test -Dtest=alluxio.worker.block.BlockStoreMetaTest#getBlockList
    - name: Flaky Testing
      run: mvn -pl core/server/worker edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=alluxio.worker.block.BlockStoreMetaTest#getBlockList -DnondexRuns=10
